[package]
name = "user-defined-types"
version = "0.1.0"
edition = "2021"
publish = false

[[bin]]
name = "elevator"
path = "exercise.rs"

[[bin]]
name = "error_handling"
path = "error_handling_exercise.rs"
